# Generated by Django 4.1.12 on 2026-05-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotencialVotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('localidade', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=64, null=True)),
                ('assinatura', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'potencial_votante',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PotencialVotanteImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='potenciais_votantes_imports/')),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em curso'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=10)),
                ('total_linhas', models.IntegerField(default=0)),
                ('processadas', models.IntegerField(default=0)),
                ('criadas', models.IntegerField(default=0)),
                ('duplicadas', models.IntegerField(default=0)),
                ('atualizadas', models.IntegerField(default=0)),
                ('erros', models.IntegerField(default=0)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('criado_por', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'potencial_votante_import',
                'ordering': ['-criado_em'],
            },
        ),
    ]
