# Generated by Django 4.1.12 on 2026-05-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potenciais_votantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potencialvotante',
            name='is_contactado',
            field=models.BooleanField(default=False),
        ),
    ]
