# Generated by Django 4.1.12 on 2024-09-18 17:16

import apps.militantes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geografia',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('concelho', models.CharField(blank=True, max_length=50, null=True)),
                ('freguesia', models.CharField(blank=True, max_length=50, null=True)),
                ('ilha', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel_detalhe', models.CharField(blank=True, max_length=2, null=True)),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('nome_norm', models.CharField(blank=True, max_length=300, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('zona', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'geografia',
            },
        ),
        migrations.CreateModel(
            name='Militantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_ficha', models.CharField(blank=True, max_length=20, null=True)),
                ('tp_associado', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_militante', models.CharField(blank=True, default='P', max_length=20, null=True)),
                ('alcunha', models.CharField(blank=True, max_length=20, null=True)),
                ('nm_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('nm_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('agregado_familiar', models.SmallIntegerField(blank=True, null=True)),
                ('profissao_atual', models.CharField(blank=True, max_length=50, null=True)),
                ('local_trabalho', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('funcao', models.CharField(blank=True, max_length=50, null=True)),
                ('grau_academica', models.CharField(blank=True, max_length=50, null=True)),
                ('area_atuacao', models.CharField(blank=True, max_length=255, null=True)),
                ('curso', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('dt_emissao_doc', models.DateField(blank=True, null=True)),
                ('dt_validade_doc', models.DateField(blank=True, null=True)),
                ('email_pessoal', models.CharField(blank=True, max_length=100, null=True)),
                ('email_trabalho', models.CharField(blank=True, max_length=100, null=True)),
                ('nr_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('nr_telefone_casa', models.IntegerField(blank=True, null=True)),
                ('nr_telemovel1', models.IntegerField(blank=True, null=True)),
                ('nr_telemovel2', models.IntegerField(blank=True, null=True)),
                ('tp_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('dt_nascimento', models.DateField(blank=True, null=True)),
                ('is_mobile', models.BooleanField(blank=True, null=True)),
                ('motivo_rejeicao', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(upload_to=apps.militantes.models.get_file_path)),
            ],
            options={
                'db_table': 'militantes',
            },
        ),
        migrations.CreateModel(
            name='Morada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('morada_atual', models.CharField(blank=True, max_length=250, null=True)),
                ('perto_de', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('geografia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='militantes.geografia')),
                ('militante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='militantes.militantes')),
            ],
            options={
                'db_table': 'morada',
            },
        ),
    ]
