# Generated by Django 4.1.12 on 2026-04-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geografia',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='militantes',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='militantes',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
