# Generated by Django 4.1.12 on 2026-05-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militantes', '0002_militantes_latlng'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitantesCallInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resenciado_fora_praia', models.SmallIntegerField(blank=True, null=True)),
                ('resenciado', models.SmallIntegerField(blank=True, null=True)),
                ('recetivo', models.SmallIntegerField(blank=True, null=True)),
                ('precisa_transporte_vota', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('data_hr_chamada', models.CharField(blank=True, max_length=20, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('id_militante', models.IntegerField(blank=True, null=True)),
                ('potencial_votante_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'militantes_call_info',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='militantes',
            name='potencial_votante_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='morada',
            name='potencial_votante_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        # The militantes_call_info table pre-exists (unmanaged model); add
        # the new potencial_votante_id column directly via SQL.
        migrations.RunSQL(
            sql=[
                "ALTER TABLE militantes_call_info ADD COLUMN IF NOT EXISTS potencial_votante_id bigint NULL;",
                "CREATE INDEX IF NOT EXISTS militantes_call_info_potencial_votante_id_idx ON militantes_call_info (potencial_votante_id);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS militantes_call_info_potencial_votante_id_idx;",
                "ALTER TABLE militantes_call_info DROP COLUMN IF EXISTS potencial_votante_id;",
            ],
        ),
    ]
