# Generated by Django 4.1.12 on 2024-09-18 17:16

import apps.quotas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('militantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'valor_pagamento',
            },
        ),
        migrations.CreateModel(
            name='PagamentoQuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('anexo_id', models.FileField(upload_to=apps.quotas.models.get_file_path)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True, null=True)),
                ('militante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='militantes.militantes')),
                ('valor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quotas.valorpagamento')),
            ],
            options={
                'db_table': 'pagamento_quotas',
            },
        ),
    ]
