# Generated by Django 4.1.12 on 2026-04-29 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleitores', '0003_eleicaoimport_atualizadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('militantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleitorMilitanteMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Pontuação 0-100')),
                ('score_nome', models.FloatField(default=0.0)),
                ('score_pai', models.FloatField(default=0.0)),
                ('score_mae', models.FloatField(default=0.0)),
                ('dt_nascimento_match', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('rejected', 'Rejeitado')], default='pending', max_length=10)),
                ('source', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_militante_matches', to=settings.AUTH_USER_MODEL)),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='militante_matches', to='eleitores.eleitores')),
                ('militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleitor_matches', to='militantes.militantes')),
            ],
            options={
                'db_table': 'militante_match',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='eleitormilitantematch',
            index=models.Index(fields=['status'], name='militante_m_status_d71c68_idx'),
        ),
        migrations.AddIndex(
            model_name='eleitormilitantematch',
            index=models.Index(fields=['eleitor', 'status'], name='militante_m_eleitor_70f9fd_idx'),
        ),
        migrations.AddIndex(
            model_name='eleitormilitantematch',
            index=models.Index(fields=['score'], name='militante_m_score_342e74_idx'),
        ),
        migrations.AddConstraint(
            model_name='eleitormilitantematch',
            constraint=models.UniqueConstraint(fields=('eleitor', 'militante'), name='uniq_eleitor_militante_match'),
        ),
    ]
