# Generated by Django 4.1.12 on 2024-09-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('militantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembleia_voto_nr', models.CharField(blank=True, max_length=1, null=True)),
                ('nr_eleitor', models.IntegerField()),
                ('votou', models.SmallIntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('anulado', models.SmallIntegerField(blank=True, null=True)),
                ('nr_bi_eleitor', models.CharField(blank=True, max_length=30, null=True)),
                ('nr_mesa', models.CharField(max_length=150)),
                ('motivo_n_votou', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'votacao',
            },
        ),
        migrations.CreateModel(
            name='Eleitores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('alcunha', models.CharField(blank=True, max_length=50, null=True)),
                ('nr_identificacao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('pai', models.CharField(blank=True, max_length=200, null=True)),
                ('mae', models.CharField(blank=True, max_length=200, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('ilha', models.CharField(blank=True, max_length=50, null=True)),
                ('conc_pais_res', models.CharField(blank=True, max_length=100, null=True)),
                ('local_cidade_res', models.CharField(blank=True, max_length=100, null=True)),
                ('morada', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.BigIntegerField(blank=True, null=True)),
                ('telemovel', models.BigIntegerField(blank=True, null=True)),
                ('status', models.BigIntegerField(blank=True, default='1', null=True)),
                ('id_obito', models.BigIntegerField(blank=True, null=True)),
                ('partido_voto', models.CharField(blank=True, max_length=20, null=True)),
                ('acompanhamento', models.SmallIntegerField(blank=True, null=True)),
                ('transporte', models.SmallIntegerField(blank=True, null=True)),
                ('tp_associado', models.CharField(blank=True, max_length=20, null=True)),
                ('desloca_outro_concelho', models.CharField(blank=True, max_length=100, null=True)),
                ('gv', models.CharField(blank=True, max_length=100, null=True)),
                ('desloca_de', models.CharField(blank=True, max_length=255, null=True)),
                ('desloca_para', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_sensibilidade', models.SmallIntegerField(blank=True, null=True)),
                ('code_regiao', models.CharField(blank=True, max_length=5, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=500, null=True)),
                ('nr_eleitor', models.IntegerField(blank=True, null=True)),
                ('nr_mesa', models.CharField(blank=True, max_length=40, null=True)),
                ('datahora_atualizacao', models.DateTimeField(auto_now=True, null=True)),
                ('militante_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='militantes.militantes')),
            ],
            options={
                'db_table': 'eleitores',
            },
        ),
    ]
