# Generated by Django 4.1.12 on 2026-04-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleitores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, null=True)),
                ('nominho', models.TextField(blank=True, null=True)),
                ('filiacao', models.TextField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('idade_eleitor', models.IntegerField(blank=True, null=True)),
                ('contato', models.TextField(blank=True, null=True)),
                ('nacionalidade', models.TextField(blank=True, null=True)),
                ('concelho', models.TextField(blank=True, null=True)),
                ('zona', models.TextField(blank=True, null=True)),
                ('nr_mesa', models.CharField(blank=True, max_length=40, null=True)),
                ('nr_eleitor', models.IntegerField(blank=True, null=True)),
                ('falecido', models.BooleanField(blank=True, default=False, null=True)),
                ('ausente', models.BooleanField(blank=True, default=False, null=True)),
                ('indeciso', models.BooleanField(blank=True, default=False, null=True)),
                ('nao_vai_votar', models.BooleanField(blank=True, default=False, null=True)),
                ('mpd', models.BooleanField(blank=True, default=False, null=True)),
                ('descarga', models.BooleanField(blank=True, default=False, null=True)),
                ('datahora_atualizacao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'eleitores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembleia_voto_nr', models.CharField(blank=True, max_length=1, null=True)),
                ('nr_eleitor', models.IntegerField()),
                ('votou', models.SmallIntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('anulado', models.SmallIntegerField(blank=True, null=True)),
                ('nr_bi_eleitor', models.CharField(blank=True, max_length=30, null=True)),
                ('nr_mesa', models.CharField(max_length=150)),
                ('motivo_n_votou', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'votacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EleicaoImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_eleicao', models.CharField(choices=[('L', 'Legislativa'), ('P', 'Presidencial'), ('A', 'Autárquica')], max_length=1)),
                ('mes_ano', models.CharField(help_text='Formato MM/YYYY', max_length=7)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='eleicao_imports/')),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em curso'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=10)),
                ('total_linhas', models.IntegerField(default=0)),
                ('processadas', models.IntegerField(default=0)),
                ('criadas', models.IntegerField(default=0)),
                ('erros', models.IntegerField(default=0)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('criado_por', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'eleicao_import',
                'ordering': ['-criado_em'],
            },
        ),
    ]
