# Generated by Django 4.1.12 on 2026-05-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0003_eleicaoimport_atualizadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadernoEleitoral2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilha', models.CharField(blank=True, default='', max_length=100)),
                ('cre', models.CharField(blank=True, default='', max_length=150)),
                ('posto', models.CharField(blank=True, default='', max_length=150)),
                ('concelho', models.CharField(blank=True, default='', max_length=150)),
                ('mesa', models.CharField(blank=True, default='', max_length=50)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('filiacao', models.TextField(blank=True, default='')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('descarga', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'caderno_eleitoral_2026',
                'ordering': ['mesa', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='CadernoEleitoral2026Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='caderno_2026_imports/')),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em curso'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=10)),
                ('total_linhas', models.IntegerField(default=0)),
                ('processadas', models.IntegerField(default=0)),
                ('criadas', models.IntegerField(default=0)),
                ('duplicadas', models.IntegerField(default=0)),
                ('atualizadas', models.IntegerField(default=0)),
                ('erros', models.IntegerField(default=0)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('criado_por', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'caderno_eleitoral_2026_import',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='cadernoeleitoral2026',
            index=models.Index(fields=['mesa'], name='caderno_ele_mesa_b37a75_idx'),
        ),
        migrations.AddIndex(
            model_name='cadernoeleitoral2026',
            index=models.Index(fields=['concelho'], name='caderno_ele_concelh_bd4165_idx'),
        ),
        migrations.AddIndex(
            model_name='cadernoeleitoral2026',
            index=models.Index(fields=['nome'], name='caderno_ele_nome_203fe2_idx'),
        ),
    ]
