# Generated by Django 4.1.12 on 2026-05-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0004_cadernoeleitoral2026_cadernoeleitoral2026import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadernoeleitoral2026',
            name='nome_mae',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cadernoeleitoral2026',
            name='nome_pai',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
