# Generated by Django 4.1.12 on 2024-09-28 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_mesa', models.CharField(max_length=150)),
                ('status', models.BigIntegerField(blank=True, default='1', null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'mesa',
            },
        ),
        migrations.CreateModel(
            name='UserMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True, null=True)),
                ('mesa', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mesa.mesa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_mesa',
            },
        ),
    ]
