# Generated by Django 4.1.12 on 2026-05-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0001_initial'),
        ('mesa', '0002_create_api_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='concelho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='territorio.concelho'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='territorio.zona'),
        ),
    ]
