# Generated by Django 4.1.12 on 2024-03-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartaConvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem_id', models.IntegerField(blank=True, null=True)),
                ('publishedAt', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
